"""add_versioning_fields

Revision ID: ad9e6c41c55f
Revises: add_org_and_project
Create Date: 2025-12-03 19:29:21.428428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad9e6c41c55f'
down_revision = 'add_org_and_project'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Clean up orphaned records before creating FKs
    # Aggressive cleanup for dev environment consistency
    # Only delete if table exists (for fresh installs)
    from sqlalchemy import inspect
    conn = op.get_bind()
    inspector = inspect(conn)
    existing_tables = inspector.get_table_names()
    
    # Create model_version_artifacts table if it doesn't exist
    if 'model_version_artifacts' not in existing_tables:
        op.create_table('model_version_artifacts',
            sa.Column('model_version_id', sa.String(length=36), nullable=False),
            sa.Column('artifact_id', sa.String(length=36), nullable=False),
            sa.Column('relevance_score', sa.Integer(), nullable=True),
            sa.PrimaryKeyConstraint('model_version_id', 'artifact_id')
        )
    else:
        # Table exists, clean up orphaned records
        op.execute("DELETE FROM model_version_artifacts")
    
    # Clean up processes with missing required fields (project_id, organization_id)
    # Must delete child versions first
    if 'model_versions' in existing_tables and 'processes' in existing_tables:
        op.execute("""
            DELETE FROM model_versions 
            WHERE process_id IN (
                SELECT id FROM processes 
                WHERE project_id IS NULL OR organization_id IS NULL
            )
        """)
        op.execute("DELETE FROM processes WHERE project_id IS NULL OR organization_id IS NULL")
    
    # Create foreign keys - check if they exist first
    # Refresh table list after potential table creation
    current_tables = inspector.get_table_names()
    if 'model_version_artifacts' in current_tables:
        # Check existing foreign keys
        fk_constraints = [fk['name'] for fk in inspector.get_foreign_keys('model_version_artifacts')]
        if not any('artifact_id' in str(fk) for fk in fk_constraints):
            op.create_foreign_key('fk_model_version_artifacts_artifact', 'model_version_artifacts', 'artifacts', ['artifact_id'], ['id'])
        if not any('model_version_id' in str(fk) for fk in fk_constraints):
            op.create_foreign_key('fk_model_version_artifacts_version', 'model_version_artifacts', 'model_versions', ['model_version_id'], ['id'])
    op.add_column('model_versions', sa.Column('commit_message', sa.String(), nullable=True))
    op.add_column('model_versions', sa.Column('change_type', sa.String(), nullable=True))
    op.add_column('model_versions', sa.Column('parent_version_id', sa.String(length=36), nullable=True))
    op.add_column('model_versions', sa.Column('is_active', sa.Boolean(), nullable=True))
    
    # Add status column if it doesn't exist
    inspector = inspect(op.get_bind())
    model_versions_columns = [col['name'] for col in inspector.get_columns('model_versions')]
    if 'status' not in model_versions_columns:
        op.add_column('model_versions', sa.Column('status', sa.String(length=20), nullable=True, server_default="'draft'"))
    else:
        op.alter_column('model_versions', 'status',
                   existing_type=sa.VARCHAR(length=20),
                   nullable=True,
                   existing_server_default=sa.text("'draft'::character varying"))
    
    op.alter_column('model_versions', 'generation_method',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('model_versions', 'generation_prompt',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_foreign_key(None, 'model_versions', 'model_versions', ['parent_version_id'], ['id'])
    op.alter_column('processes', 'project_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('processes', 'organization_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.drop_index('ix_processes_organization_id', table_name='processes')
    op.drop_index('ix_processes_project_id', table_name='processes')
    op.drop_index('ix_projects_organization_id', table_name='projects')
    op.drop_index('ix_users_organization_id', table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_users_organization_id', 'users', ['organization_id'], unique=False)
    op.create_index('ix_projects_organization_id', 'projects', ['organization_id'], unique=False)
    op.create_index('ix_processes_project_id', 'processes', ['project_id'], unique=False)
    op.create_index('ix_processes_organization_id', 'processes', ['organization_id'], unique=False)
    op.alter_column('processes', 'organization_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('processes', 'project_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.drop_constraint(None, 'model_versions', type_='foreignkey')
    op.alter_column('model_versions', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'draft'::character varying"))
    op.alter_column('model_versions', 'generation_prompt',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('model_versions', 'generation_method',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_column('model_versions', 'is_active')
    op.drop_column('model_versions', 'parent_version_id')
    op.drop_column('model_versions', 'change_type')
    op.drop_column('model_versions', 'commit_message')
    op.drop_constraint(None, 'model_version_artifacts', type_='foreignkey')
    op.drop_constraint(None, 'model_version_artifacts', type_='foreignkey')
    # ### end Alembic commands ###
